version: "3.9"

volumes:
  neo4j-data:

networks:
  local-bridge:
    external: true

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    hostname: neo4j
    restart: "no"
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      local-bridge:
        ipv4_address: 192.168.2.7
    volumes:
      - neo4j-data:/data
      - ./import:/var/lib/neo4j/import/
