volumes:
  data:

networks:
  local-bridge:
    external: true

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    hostname: sonarqube
    restart: "no"
    ports:
      - "9000:9000"
    networks:
      local-bridge:
    volumes:
      - data:/var/lib/sonarqube
