version: "3.9"

networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    restart: "no"
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      spark-network:
        ipv4_address: 192.168.3.2
    volumes:
      - /mnt/spark-apps:/opt/spark-apps
      - /mnt/spark-data:/opt/spark-data
    environment:
      - SPARK_MODE=master

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    restart: "no"
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
#    env_file: ./env/spark-worker.sh
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      spark-network:
        ipv4_address: 192.168.3.3
    volumes:
      - /mnt/spark-apps:/opt/spark-apps
      - /mnt/spark-data:/opt/spark-data
