version: "3.9"

volumes:
  zookeeper-tls-data:
  kafka-tls-data:

services:
  zookeeper-tls:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper-tls
    restart: "no"
    volumes:
      - zookeeper-tls-data:/var/lib/zookeeper/data
    ports:
      - "2181:2181"
    environment:
      # ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_SERVER_ID: 1
#      ZOOKEEPER_TICK_TIME: 2000
#      ZOOKEEPER_INIT_LIMIT: 5
#      ZOOKEEPER_SYNC_LIMIT: 2
#      ZOOKEEPER_SERVERS: localhost:22181,localhost:32181,localhost:42181

  kafka-tls:
    image: confluentinc/cp-kafka
    container_name: kafka-tls
    restart: "no"
    depends_on:
     - zookeeper-tls
    volumes:
     - ./secrets:/etc/kafka/secrets
     - kafka-tls-data:/var/lib/kafka/data
    ports:
     - "9092:9092"
    environment:
     ALLOW_PLAINTEXT_LISTENER: "no"
    #     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: "zookeeper-tls:2181"
     KAFKA_LISTENERS: "SSL://localhost:9092"
     KAFKA_ADVERTISED_LISTENERS: "SSL://localhost:9092"
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     # KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
     # KAFKA_SSL_KEYSTORE_FILENAME: "kafka-keystore.pfx"
     # KAFKA_SSL_TRUSTSTORE_FILENAME: "kafka-truststore.pfx"
     # KAFKA_SSL_TRUSTSTORE_TYPE: "PKCS12"
     KAFKA_SSL_KEYSTORE_FILENAME: "kafka.broker1.keystore.jks"
     KAFKA_SSL_KEYSTORE_CREDENTIALS: "broker1_keystore_creds"
     KAFKA_SSL_KEY_CREDENTIALS: "broker1_sslkey_creds"
     KAFKA_SSL_TRUSTSTORE_FILENAME: "kafka.broker1.truststore.jks"
     KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "broker1_truststore_creds"
     KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
     # KAFKA_SSL_CLIENT_AUTH: requested
     KAFKA_SSL_CLIENT_AUTH: "required"
     KAFKA_SECURITY_INTER_BROKER_PROTOCOL: "SSL"
     KAFKA_SSL_PROTOCOL: "TLSv1.2"
