version: "3.9"

networks:
  local-bridge:
    external: true

volumes:
  data:

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: "no"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - data:/var/lib/mongo
    networks:
      local-bridge:
        ipv4_address: 192.168.2.8

#   mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: root
