version: "3.9"

volumes:
  data:

networks:
  local-bridge:
    external: true

services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: "no"
    ports:
      - "6379:6379"
    volumes:
      - data:/var/lib/redis
    networks:
      local-bridge:
        ipv4_address: 192.168.2.6
